# -*- coding: utf-8 -*-
"""Multimodal RAG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nWs4RzqO-LRJYFUbtWSSY09C4bF61rPh

# Step 1 - Setup
"""

# Import the userdata module from Google Colab
from google.colab import userdata
# Retrieve the API key stored under 'genai_course' from Colab's userdata
api_key = userdata.get('genai_course')

# Mount the drive
from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# Change directory to this folder
# %cd /content/drive/MyDrive/GenAI/RAG/Multimodal RAG

"""# Step 2 - Get the data"""

# Define the Video Path
video_path = "decision-making-course.mp4"

"""# Step 3 - Extract the Audio and Compress"""

# Install libraries for audio processing and  handling multimedia files
!pip install -q pydub
!apt-get install -q ffmpeg

# Import Libraries
import os
import subprocess
from pydub import AudioSegment

# Define the audio path
audio_output_path = "audios/output.mp3"

# Ensure the output directory exists
output_dir = os.path.dirname(audio_output_path)
# Create the directory if it does not already exist
if not os.path.exists(output_dir):
    os.makedirs(output_dir)

# Ensure the output file has the correct extension
if not audio_output_path.endswith(".mp3"):
    audio_output_path += ".mp3"

# Construct the ffmpeg command to extract the audio
command = [
    'ffmpeg',
    '-y', # overwrites if the audio exists
    '-i', video_path, # input file
    '-vn', # No video
    '-acodec', 'libmp3lame', # Audio codecs
    audio_output_path # output file
]

# execute the command to extract the audio
subprocess.run(command, check = True)

# Set the bitrate
bitrate = "32k"

# Set path for compressed audio
compressed_audio_path = "audios/compressed.mp3"

# Construct the ffmpeg command to compress the audio
command = [
    'ffmpeg',
    '-y',                    # Overwrite output file if it exists
    '-i', audio_output_path, # Input audio file path
    '-ab', bitrate,          # Audio bitrate for compression
    compressed_audio_path    # Output compressed audio file path
]

# Execute the ffmpeg command to compress the audio
subprocess.run(command, check=True)

"""# Step 4 - Transcribe Audio using OpenAI API"""

# Import OpenAI library
from openai import OpenAI

# Connect to the OpenAI API
client = OpenAI(api_key = api_key)

# Open the compressed audio file in binary mode
with open(compressed_audio_path, "rb") as file:
    # Use the Whisper model to transcribe the audio
    transcript = client.audio.transcriptions.create(
        model="whisper-1",    # Specify the model to use for transcription
        file=file             # Provide the audio file for transcription
    )

# Inspect the transcript
transcript.text

# Define the path where the transcription will be saved
transcript_path = "transcripts/transcript.txt"

# Ensure the output directory exists
output_dir = os.path.dirname(transcript_path)
# Create the directory if it does not already exist
if not os.path.exists(output_dir):
    os.makedirs(output_dir)

# Save the transcribed text to a file
with open(transcript_path, "w") as file:
  file.write(transcript.text) # .text is the attribute from transcrition

# # Save the transcribed text without using "with"
# file = open(transcript_path, "w")
# file.write(transcript.text)
# file.close()

"""# Step 5 - Extract Frames from the video"""

# Install the moviepy library to handle video data
!pip install -q moviepy

# Load moviepy library
from moviepy.editor import VideoFileClip

# Define the output folder for storing frames
output_folder = "frames"
# Create the folder if it does not already exist
if not os.path.exists(output_folder):
    os.makedirs(output_folder)

# Load the video
video = VideoFileClip(video_path)

# Extract frames from the video at regular intervals
frame_paths = []
interval = 10  # Time interval between frames in seconds

for t in range(0, int(video.duration), interval):
    # Construct the file path for each frame
    frame_path = os.path.join(output_folder, f"frame_{t:04d}.png")

    # Save the frame at the specified time
    video.save_frame(frame_path, t)

    # Append the path of the saved frame to the list
    frame_paths.append(frame_path)

"""# Step 6 - Embedding Audio"""

# Import libraries
from transformers import CLIPProcessor, CLIPModel, CLIPTokenizer
import torch
import numpy as np

# Load the Model, Processor and Tokenizer
model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32")
processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")
tokenizer = CLIPTokenizer.from_pretrained("openai/clip-vit-base-patch32")

# Read the transcribed text from the file
with open(transcript_path, "r") as file:
  transcript_text = file.read()

# Tokenize the entire transcript text
tokens = tokenizer(transcript_text,
                   return_tensors="pt",  # Return tensors for PyTorch
                   padding=True)         # Pad sequences to the same length

# Extract the input_ids from the tokenized output
tokens = tokens['input_ids'][0]

# Print the number of tokens
print(f"The number of tokens is {len(tokens)}")

# The CLIP model requires 77 tokens per chunk
max_tokens = 77
transcription_chunks = []

# Split the tokens into chunks of up to max_tokens tokens each
for i in range(0, len(tokens), max_tokens):
    chunk = tokens[i:i+max_tokens]
    transcription_chunks.append(chunk)

# Print the number of chunks created
print(f"The number of chunks is {len(transcription_chunks)}")

# Inspect the transcription_chunks
transcription_chunks

# Text Embeddings -> embed the tokens in each chunk
text_embeddings = []

for chunk in transcription_chunks:
  # Ensure the chunk is in the correct shape for the model
  inputs = {"input_ids": chunk.unsqueeze(0)}

  # Get the text embedding for the chunk
  with torch.no_grad():
    text_embedding = model.get_text_features(**inputs)
    # Convert the embedding to a numpy array and flatten it
    text_embeddings.append(text_embedding.cpu().numpy().flatten())

# Convert the list of embeddings to a numpy array
text_embedding_np = np.array(text_embeddings)

# Print the shape of the text embeddings array
print(f"Text embedding shape is {text_embedding_np.shape}")

# Inspect the text embeddings numpy array
text_embedding_np

"""# Step 7 - embedding the images"""

# Import the PIL library
from PIL import Image

# Embed the images
frames_folder = "frames"
image_embeddings = []
image_paths = []

for frame_file in os.listdir(frames_folder):
  if frame_file.endswith('.png'):
    # Construct the path to the image file
    frame_path = os.path.join(frames_folder, frame_file)
    image_paths.append(frame_path)

    # Load and preprocess the image
    image = Image.open(frame_path)
    inputs = processor(images = image, return_tensors = "pt")

    # Generate the image embeddings
    with torch.no_grad():
      image_embedding = model.get_image_features(**inputs)
      # Convert the embedding to a numpy array and flatten it
      image_embeddings.append(image_embedding.cpu().numpy().flatten())

# Convert the list of embeddings to a numpy array
image_embedding_np = np.array(image_embeddings)

# Print the shape
print(f"Image embedding shape is {image_embedding_np.shape}")

# Inspect the image embedding numpy array
image_embedding_np

"""# Step 8 - Contrastive Learning"""

# Import Libraries
from sklearn.metrics.pairwise import cosine_similarity
import matplotlib.pyplot as plt
import random

# Calculate the cosine similarity matrix between text and image embeddings
similarities = cosine_similarity(text_embedding_np,
                                 image_embedding_np)

# Print the cosine similarity matrix
similarities

# Check the shape of the similarities
print(f"The shape of the similarities is {similarities.shape}")

# Retrieve the top-k most similar images for each text chunk
top_k = 5
for i, text_chunk in enumerate(similarities):
  # Get indices of the top-k most similar images
  similar_indices = text_chunk.argsort()[-top_k:][::-1]
  print(f"Top {top_k} images for each chunk {i}: {similar_indices}")

# Set a random seed for reproducibility
random.seed(1502)

# Select 5 random text chunk indices
random_text_indices = random.sample(range(len(text_embedding_np)), 5)
print(f"Random text chunk indices: {random_text_indices}")

# Find the 3 most similar images for each randomly selected text chunk
text_to_images_similarities = []
for idx in random_text_indices:
  # Get indices of the top 3 most similar images for the text chunk
  similar_images = similarities[idx].argsort()[-3:][::-1]
  text_to_images_similarities.append(similar_images)

# Data visualization of the text and images
for i, text_index in enumerate(random_text_indices):
  plt.figure(figsize = (10,8))

   # Displaying the text chunk
  print(f"""
  The text chunk {i + 1}: {' '.join([tokenizer.decode([token]) for token in transcription_chunks[text_index]]
  )}""")

  # Displaying similar images corresponding to the current text chunk
  for j, image_idx in enumerate(text_to_images_similarities[i]):
    image = Image.open(image_paths[image_idx])
    plt.subplot(1, 3, j + 1)
    plt.imshow(image)
    plt.axis('off')
    plt.title(f"Image {j + 1}")

  plt.show() # Show the plot with images and text

"""# Step 9 - Retrieval system"""

# Let's define a query
query = "Which cognitive biases are discussed?"

# Tokenizing the query
query_tokens = tokenizer(query,
                         return_tensors = "pt",       # Return tensors in PyTorch format
                         padding = True)['input_ids'] # Pad tokens to ensure consistent length

# Generate the query embeddings in the joint embedding space
# Use the CLIP model to compute text features
with torch.no_grad():
  query_embedding = model.get_text_features(
      input_ids = query_tokens  # Pass tokenized query to model
  ).cpu().numpy().flatten()     # Convert to numpy array and flatten to 1D

# Print shape of the embedding
print(f"The shape of the query embedding is {query_embedding.shape}")

# Compute the cosine similarity between the query and the transcripts
text_similarities = cosine_similarity([query_embedding], text_embedding_np)[0]
text_similarities

# Define how many chunks we want
top_k_texts = 10

# Retrieve the indices of the top-k most similar text_chunks
top_k_text_indices = text_similarities.argsort()[-top_k_texts:][::-1]
top_k_text_indices

# Retrieve the closest images for each text chunk
top_k_images_indices = []
images_per_chunk = 2 # Number of top similar images to retrieve for each text chunk

for idx in top_k_text_indices:
  # Find indices of the top-k similar images for the current text chunk
  similar_images = similarities[idx].argsort()[-images_per_chunk:][::-1]
  top_k_images_indices.append(similar_images)  # Add to the list

# Remove any duplicates and limit to the top k images
top_k_images_indices = list(set([item for sublist in top_k_images_indices for item in sublist]))

# Print the number of unique image indices
print(f"The total images indices are {len(top_k_images_indices)}")

"""# Step 10 - Generation system"""

import base64

# Combining the retrieved text chunks
retrieved_text = []

for idx in top_k_text_indices:
  # Decode and append each text chunk using the tokenizer
  retrieved_text.append(tokenizer.decode(transcription_chunks[idx]))

# Join all the text chunks into a single string
retrieved_text = ' '.join(retrieved_text)
retrieved_text

# Convert the images and append them
base64frames = []

for idx in top_k_images_indices:
  image_path = image_paths[idx]  # Get the path of the image

  # Open the image file in binary read mode
  with open(image_path, "rb") as image_file:
    # Encode the image file content to base64 and decode to UTF-8 string
    base64_image = base64.b64encode(image_file.read()).decode('utf-8')
    base64frames.append(base64_image) # Append the encoded image string to the list

base64frames

# Define the model
MODEL = "gpt-4o-mini"

# Define the system prompt
system_prompt = """
You are an expert teacher that summarises visual and transcribed content
"""

# Prepare the user message content
user_message_content = [
    "These are the frames from the video",                                # Initial message indicating the following content
    *map(lambda x: {"type": "image_url",                                  # Map each base64-encoded image to the appropriate format
                    "image_url": {"url": f'data:image/jpg;base64,{x}',
                                 "detail": "high"}},
         base64frames),
    {"type": "text",                                                      # Append the retrieved text as a separate message
     "text": retrieved_text}
]

# Call the OpenAI API to generate a summary
response = client.chat.completions.create(
    model = MODEL, # Specify the model to use for the completion
    messages = [
        {"role": "system", "content": system_prompt}, # Provide system prompt to guide the model
        {"role": "user", "content": user_message_content}, # Provide user message content with images and text
    ],
    temperature = 0.3,  # Set the temperature to control the randomness of the output
)

# Generate the response
generated_response = response.choices[0].message.content
print(generated_response)

